import {Package,ShoppingBag,Users,Sprout,Wallet,UserRound,Star,ClipboardCheck} from "lucide-react";
import Link from "next/link";
import StatCard from "@/components/dashboard/StatCard";
import {formatCurrency} from "@/lib/productUtils";
import VerificationBadge from "./VerificationBadge";
import "./phase4.css";
export default function AnalyticsStats({role,data:d}) {
 const stats=role==="ADMIN"?[["Total Users",d.users,Users],["Farmers",d.farmers,Sprout],["Buyers",d.buyers,UserRound],["Pending Verification",d.pendingVerification,ClipboardCheck],["Verified Farmers",d.verifiedFarmers,Sprout],["Products",d.products,Package],["Orders",d.orders,ShoppingBag],["Platform Order Value",formatCurrency(d.value),Wallet]]:role==="FARMER"?[["Total Products",d.products,Package],["Active Products",d.active,Package],["Out of Stock",d.outOfStock,Package],["Total Orders",d.orders,ShoppingBag],["Pending Orders",d.pending,ShoppingBag],["Delivered Orders",d.delivered,ClipboardCheck],["Revenue",formatCurrency(d.revenue),Wallet],["Average Rating",d.rating.toFixed(1)+" / 5",Star]]:[["Total Orders",d.orders,ShoppingBag],["Pending Orders",d.pending,ShoppingBag],["Delivered Orders",d.delivered,ClipboardCheck],["Total Spending",formatCurrency(d.spending),Wallet],["Cart Items",d.cartItems,Package],["Reviews Given",d.reviews,Star]];
 return <><div className="stats-grid">{stats.map(([label,value,Icon])=><StatCard key={label} label={label} value={value} icon={Icon}/>)}</div><p className="analytics-note">{role==="ADMIN"?"Platform order value includes delivered orders only.":role==="FARMER"?"Revenue includes delivered orders only. Rating is calculated from "+d.ratingCount+" reviews.":"Spending includes delivered orders only. Cart items counts distinct products."}</p><section className="phase4-card"><h2>{d.orders?"Your workspace":"Ready for your first order"}</h2>{role==="FARMER"&&<p>Verification: {d.verificationStatus} <VerificationBadge status={d.verificationStatus}/></p>}<div className="phase4-actions">{role==="FARMER"?<><Link href="/farmer/products">Manage Products →</Link><Link href="/farmer/orders">View Orders →</Link></>:role==="ADMIN"?<Link href="/admin/farmers">Review Farmer Verification →</Link>:<><Link href="/marketplace">Browse Marketplace →</Link><Link href="/buyer/orders">View Orders →</Link></>}<Link href="/notifications">Notifications →</Link></div></section></>;
}

